name: entity_store

packages:
  - packages/**

scripts:
  analyze: melos exec -- "dart analyze ."
  gen: melos exec -- "flutter pub run build_runner watch --delete-conflicting-outputs"
  get: melos exec -- "flutter pub get" 
  upgrade: melos exec -- "flutter pub upgrade"