name: entity_store
description: Entity State Management Package
version: 2.0.0
homepage: https://github.com/soraef/entity_store/tree/main/packages/entity_store

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  type_result: ^1.0.2
  state_notifier: ^0.7.2+1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
