name: entity_store
description: Entity State Management Package
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  skyreach_result: ^1.0.1
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
