name: todo_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3

  # State Management
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1

  # Freezed
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  # Dialog UI Helper
  adaptive_dialog: ^1.8.0+1

  uuid: ^3.0.6

  entity_store: 
    path: ../../packages/entity_store
  
  entity_store_firestore: 
    path: ../../packages/entity_store_firestore

dependency_overrides:
  entity_store: 
    path: ../../packages/entity_store
  
  entity_store_firestore: 
    path: ../../packages/entity_store_firestore


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
