name: entity_store_sembast
description: sembast operations for entity_store package
version: 7.0.0
homepage: https://github.com/soraef/entity_store/tree/main/packages/entity_store_sembast

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sembast: ^3.5.0+1
  entity_store: ^7.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
